services:
    
  kit.rental.web:
    image: ghcr.io/robotikbilim/kit-rental-web:sha256-90ab47df9275efabd8888e1504cb206340ffdba8e9f9ec267a5ae831494ac7e0
    container_name: kit_rental_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "93"
    restart: always
    networks:
      - external-net
    volumes:
      - /root/projects/shared/nginx/ssl/ca-root.crt:/usr/local/share/ca-certificates/sectigo-root.crt:ro
      - /root/projects/shared/nginx/ssl/ca-intermediate.crt:/usr/local/share/ca-certificates/sectigo-intermediate.crt:ro

  kit.rental.gateway:
    image: ghcr.io/robotikbilim/kit-rental-gateway:sha256-a00acacc82a437f3c43afd7e61af641f3139b8be16541e659309dead89c1b8cc
    container_name: kit_rental_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "92"
    restart: always
    networks:
      - external-net

  kit.rental.core:
    image: ghcr.io/robotikbilim/kit-rental-core:sha256-474d5c18fc8d68fedb63502ac44de71410fa09e0d25700eb5e516cd84074f65d
    container_name: kit_rental_core
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "91"
    restart: always
    networks:
      - external-net

  kit.rental.identity:
    image: ghcr.io/robotikbilim/kit-rental-identity:sha256-0a7733c238b80fd3845ca904a1a412b7b6e2c59d54fd7841789d67741107ba22
    container_name: kit_rental_identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "90"
    restart: always
    networks:
      - external-net
  
networks:
  external-net:
    external: true