<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\KitRental.BuildingBlocks\src\KitRental.SharedKernel\KitRental.SharedKernel.csproj" />
  </ItemGroup>
</Project>
