// <auto-generated />
using KitRental.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KitRental.Core.Infrastructure.Persistence.Migrations;

[DbContext(typeof(KitRentalDbContext))]
[Migration("20260929110000_AddKitOwnershipPayments")]
partial class AddKitOwnershipPayments
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) =>
        new KitRentalDbContextModelSnapshot().PopulateModel(modelBuilder);
}
